// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAttendanceData = "attendance_data"

// AttendanceData mapped from table <attendance_data>
type AttendanceData struct {
	AttendanceDataID            string  `gorm:"column:attendance_data_id;primaryKey" json:"attendance_data_id"`
	AttendanceDay               string  `gorm:"column:attendance_day;not null" json:"attendance_day"`
	UserID                      string  `gorm:"column:user_id;not null" json:"user_id"`
	AttendanceType              string  `gorm:"column:attendance_type;not null" json:"attendance_type"`
	AttendanceMorningType       *string `gorm:"column:attendance_morning_type" json:"attendance_morning_type"`
	AttendanceMorningTime       *string `gorm:"column:attendance_morning_time" json:"attendance_morning_time"`
	AttendanceMorningLocation   *string `gorm:"column:attendance_morning_location" json:"attendance_morning_location"`
	AttendanceAfternoonType     *string `gorm:"column:attendance_afternoon_type" json:"attendance_afternoon_type"`
	AttendanceAfternoonTime     *string `gorm:"column:attendance_afternoon_time" json:"attendance_afternoon_time"`
	AttendanceAfternoonLocation *string `gorm:"column:attendance_afternoon_location" json:"attendance_afternoon_location"`
	DayErrorInfo                *string `gorm:"column:day_error_info" json:"day_error_info"`
	CreateTime                  *string `gorm:"column:create_time" json:"create_time"`
}

// TableName AttendanceData's table name
func (*AttendanceData) TableName() string {
	return TableNameAttendanceData
}

func (*AttendanceData) PrimaryKey() []string {
	return []string{"attendance_data_id"}
}