// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDbscriptIssueList = "dbscript_issue_list"

// DbscriptIssueList mapped from table <dbscript_issue_list>
type DbscriptIssueList struct {
	ID              int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DbscriptIssueID string     `gorm:"column:dbscript_issue_id;not null" json:"dbscript_issue_id"`
	DbscriptEventID string     `gorm:"column:dbscript_event_id;not null" json:"dbscript_event_id"`
	IssueKey        *string    `gorm:"column:issue_key" json:"issue_key"`
	IssueTitle      *string    `gorm:"column:issue_title" json:"issue_title"`
	IssueStatusText *string    `gorm:"column:issue_status_text" json:"issue_status_text"`                        // ISSUE状态的中文表示
	CreateTime      *time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 记录创建时间（数据库自动写入）
	ModifyTime      *time.Time `gorm:"column:modify_time;not null;default:CURRENT_TIMESTAMP" json:"modify_time"` // 记录修改时间（数据库自动写入）
	Comments        *string    `gorm:"column:comments" json:"comments"`                                          // 备注说明
}

// TableName DbscriptIssueList's table name
func (*DbscriptIssueList) TableName() string {
	return TableNameDbscriptIssueList
}

func (*DbscriptIssueList) PrimaryKey() []string {
	return []string{"id"}
}