// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDeployEvent = "deploy_event"

// DeployEvent mapped from table <deploy_event>
type DeployEvent struct {
	DepEventID   string     `gorm:"column:dep_event_id;primaryKey" json:"dep_event_id"`
	OpUser       string     `gorm:"column:op_user;not null" json:"op_user"`
	OpTime       *time.Time `gorm:"column:op_time" json:"op_time"`
	DepStatu     *int32     `gorm:"column:dep_statu" json:"dep_statu"` // -1 状态未写入，0 失败 ，1成功，2部分失败，3 未知
	HospitalCode *string    `gorm:"column:hospital_code" json:"hospital_code"`
	CreateTime   *time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 记录创建时间（数据库自动写入）
	ModifyTime   *time.Time `gorm:"column:modify_time;not null;default:CURRENT_TIMESTAMP" json:"modify_time"` // 记录修改时间（数据库自动写入）
	Comments     *string    `gorm:"column:comments" json:"comments"`                                          // 备注说明
}

// TableName DeployEvent's table name
func (*DeployEvent) TableName() string {
	return TableNameDeployEvent
}

func (*DeployEvent) PrimaryKey() []string {
	return []string{"dep_event_id"}
}