// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDeployTask = "deploy_task"

// DeployTask mapped from table <deploy_task>
type DeployTask struct {
	DeployTaskID         string     `gorm:"column:deploy_task_id;not null" json:"deploy_task_id"`
	DeployConfigJSON     *string    `gorm:"column:deploy_config_json" json:"deploy_config_json"`
	ServerEnvID          *string    `gorm:"column:server_env_id" json:"server_env_id"`
	OpUser               *string    `gorm:"column:op_user" json:"op_user"`
	Step                 *string    `gorm:"column:step" json:"step"`
	ServerStatus         *string    `gorm:"column:server_status" json:"server_status"`
	UserStatus           *string    `gorm:"column:user_status" json:"user_status"`
	SoftStatus           *string    `gorm:"column:soft_status" json:"soft_status"`
	WarStatus            *string    `gorm:"column:war_status" json:"war_status"`
	ParamStatus          *string    `gorm:"column:param_status" json:"param_status"`
	DeployTasklistStatus *string    `gorm:"column:deploy_tasklist_status" json:"deploy_tasklist_status"`
	PreStatus            *string    `gorm:"column:pre_status" json:"pre_status"`
	EnvStatus            *string    `gorm:"column:env_status" json:"env_status"`
	IsNewest             *string    `gorm:"column:is_newest" json:"is_newest"`
	CreateTime           *time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	ModifyTime           *time.Time `gorm:"column:modify_time;not null;default:CURRENT_TIMESTAMP" json:"modify_time"`
	Comments             *string    `gorm:"column:comments" json:"comments"`
}

// TableName DeployTask's table name
func (*DeployTask) TableName() string {
	return TableNameDeployTask
}

func (*DeployTask) PrimaryKey() []string {
	return []string{}
}