// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFileData = "file_data"

// FileData mapped from table <file_data>
type FileData struct {
	FileID          string     `gorm:"column:file_id;primaryKey" json:"file_id"`
	TargetID        *string    `gorm:"column:target_id" json:"target_id"`
	FileServiceType *string    `gorm:"column:file_service_type" json:"file_service_type"`
	Size            *int64     `gorm:"column:size" json:"size"`
	Data            *[]byte    `gorm:"column:data" json:"data"`
	Name            *string    `gorm:"column:name" json:"name"`
	CreateTime      *time.Time `gorm:"column:create_time" json:"create_time"`
	ModifyTime      *time.Time `gorm:"column:modify_time" json:"modify_time"`
	OpUser          *string    `gorm:"column:op_user" json:"op_user"`
	FileType        *string    `gorm:"column:file_type" json:"file_type"`
}

// TableName FileData's table name
func (*FileData) TableName() string {
	return TableNameFileData
}

func (*FileData) PrimaryKey() []string {
	return []string{"file_id"}
}