// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameInstallOsUser801 = "install_os_user_801"

// InstallOsUser801 mapped from table <install_os_user_801>
type InstallOsUser801 struct {
	Softid   string  `gorm:"column:softid;not null" json:"softid"`
	Userosid *string `gorm:"column:userosid" json:"userosid"`
}

// TableName InstallOsUser801's table name
func (*InstallOsUser801) TableName() string {
	return TableNameInstallOsUser801
}

func (*InstallOsUser801) PrimaryKey() []string {
	return []string{}
}