// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameIssueCommit = "issue_commit"

// IssueCommit mapped from table <issue_commit>
type IssueCommit struct {
	CommitIssueID string  `gorm:"column:commit_issue_id;primaryKey" json:"commit_issue_id"`
	ProjectURL    string  `gorm:"column:project_url;not null" json:"project_url"`
	ProjectName   string  `gorm:"column:project_name;not null" json:"project_name"`
	IssueKey      *string `gorm:"column:issue_key" json:"issue_key"`
	Created       *string `gorm:"column:created" json:"created"`
	Commit        *string `gorm:"column:commit" json:"commit"`
	Body          *string `gorm:"column:body" json:"body"`
	Username      *string `gorm:"column:username" json:"username"`
}

// TableName IssueCommit's table name
func (*IssueCommit) TableName() string {
	return TableNameIssueCommit
}

func (*IssueCommit) PrimaryKey() []string {
	return []string{"commit_issue_id"}
}