// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameItResourceNode = "it_resource_node"

// ItResourceNode mapped from table <it_resource_node>
type ItResourceNode struct {
	NodeID     int32   `gorm:"column:node_id;primaryKey;autoIncrement:true" json:"node_id"`
	NodeType   *string `gorm:"column:node_type" json:"node_type"`                // 节点类型
	NodePid    string  `gorm:"column:node_pid;not null" json:"node_pid"`         // 节点父ID
	NodeBusiID string  `gorm:"column:node_busi_id;not null" json:"node_busi_id"` // 节点对应的业务类型的主键
	NodeText   *string `gorm:"column:node_text" json:"node_text"`                // 节点描述
	/*
		节点状态
		open
		closed
	*/
	NodeState   *string    `gorm:"column:node_state" json:"node_state"`
	NodeURL     *string    `gorm:"column:node_url" json:"node_url"`                                          // 节点超链接
	NodeIconCls *string    `gorm:"column:node_iconCls" json:"node_iconCls"`                                  // 节点图标
	CreateTime  *time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 记录创建时间（数据库自动写入）
	ModifyTime  *time.Time `gorm:"column:modify_time;not null;default:CURRENT_TIMESTAMP" json:"modify_time"` // 记录修改时间（数据库自动写入）
	Comments    *string    `gorm:"column:comments" json:"comments"`                                          // 备注说明
}

// TableName ItResourceNode's table name
func (*ItResourceNode) TableName() string {
	return TableNameItResourceNode
}

func (*ItResourceNode) PrimaryKey() []string {
	return []string{"node_id"}
}