// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessageSendLog = "message_send_log"

// MessageSendLog mapped from table <message_send_log>
type MessageSendLog struct {
	MessageSendLogID string     `gorm:"column:message_send_log_id;primaryKey" json:"message_send_log_id"`
	SendTime         *time.Time `gorm:"column:send_time" json:"send_time"`                                        // 发送消息时间
	SendUserid       *string    `gorm:"column:send_userid" json:"send_userid"`                                    // 执行发送消息的用户ID
	SendContent      *string    `gorm:"column:send_content" json:"send_content"`                                  // 发送消息的内容
	MessageTargetID  *string    `gorm:"column:message_target_id" json:"message_target_id"`                        // 发送对象ID
	SendStatu        *string    `gorm:"column:send_statu" json:"send_statu"`                                      // 1 已发送 0未发送
	CreateTime       *time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 记录创建时间（数据库自动写入）
	ModifyTime       *time.Time `gorm:"column:modify_time;not null;default:CURRENT_TIMESTAMP" json:"modify_time"` // 记录修改时间（数据库自动写入）
	Comments         *string    `gorm:"column:comments" json:"comments"`                                          // 备注说明
}

// TableName MessageSendLog's table name
func (*MessageSendLog) TableName() string {
	return TableNameMessageSendLog
}

func (*MessageSendLog) PrimaryKey() []string {
	return []string{"message_send_log_id"}
}