// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMsgSendchannelProvider = "msg_sendchannel_provider"

// MsgSendchannelProvider mapped from table <msg_sendchannel_provider>
type MsgSendchannelProvider struct {
	MsgSendProviderID    string  `gorm:"column:msg_send_provider_id;primaryKey" json:"msg_send_provider_id"`
	ProviderName         *string `gorm:"column:provider_name" json:"provider_name"`
	WxCorpid             *string `gorm:"column:wx_corpid" json:"wx_corpid"`
	WxSecret             *string `gorm:"column:wx_secret" json:"wx_secret"`
	WxBaseURL            *string `gorm:"column:wx_base_url" json:"wx_base_url"`
	WxAgentID            *string `gorm:"column:wx_agentId" json:"wx_agentId"`
	WxTouser             *string `gorm:"column:wx_touser" json:"wx_touser"`
	WxToparty            *string `gorm:"column:wx_toparty" json:"wx_toparty"`
	DingRobotURL         *string `gorm:"column:ding_robot_url" json:"ding_robot_url"`
	MailSender           *string `gorm:"column:mail_sender" json:"mail_sender"`
	MailUsername         *string `gorm:"column:mail_username" json:"mail_username"`
	MailPwd              *string `gorm:"column:mail_pwd" json:"mail_pwd"`
	MailReciveUsers      *string `gorm:"column:mail_recive_users" json:"mail_recive_users"`
	MailReciveUserGroups *string `gorm:"column:mail_recive_user_groups" json:"mail_recive_user_groups"`
	ProviderType         *string `gorm:"column:provider_type" json:"provider_type"`
	DingRobotKeywords    *string `gorm:"column:ding_robot_keywords" json:"ding_robot_keywords"`
	DingRobotSign        *string `gorm:"column:ding_robot_sign" json:"ding_robot_sign"`
	DingRobotIP          *string `gorm:"column:ding_robot_ip" json:"ding_robot_ip"`
	MasReciveUsers       *string `gorm:"column:mas_recive_users" json:"mas_recive_users"`
	MasReciveUserGroups  *string `gorm:"column:mas_recive_user_groups" json:"mas_recive_user_groups"`
	MasRecivePthones     *string `gorm:"column:mas_recive_pthones" json:"mas_recive_pthones"`
	MasSenderUser        *string `gorm:"column:mas_sender_user" json:"mas_sender_user"`
	MasSenderPwd         *string `gorm:"column:mas_sender_pwd" json:"mas_sender_pwd"`
	MasSenderName        *string `gorm:"column:mas_sender_name" json:"mas_sender_name"`
	MasSenderURL         *string `gorm:"column:mas_sender_url" json:"mas_sender_url"`
	MasType              *string `gorm:"column:mas_type" json:"mas_type"`
	MasSign              *string `gorm:"column:mas_sign" json:"mas_sign"`
	MasOther1            *string `gorm:"column:mas_other_1" json:"mas_other_1"`
	MasOther2            *string `gorm:"column:mas_other_2" json:"mas_other_2"`
	MasOther3            *string `gorm:"column:mas_other_3" json:"mas_other_3"`
	MailSenderSMTP       *string `gorm:"column:mail_sender_smtp" json:"mail_sender_smtp"`
	MailSenderSMTPPort   *int32  `gorm:"column:mail_sender_smtp_port" json:"mail_sender_smtp_port"`
	MailReciveAddress    *string `gorm:"column:mail_recive_address" json:"mail_recive_address"`
}

// TableName MsgSendchannelProvider's table name
func (*MsgSendchannelProvider) TableName() string {
	return TableNameMsgSendchannelProvider
}

func (*MsgSendchannelProvider) PrimaryKey() []string {
	return []string{"msg_send_provider_id"}
}