// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOracleRpt = "oracle_rpt"

// OracleRpt mapped from table <oracle_rpt>
type OracleRpt struct {
	OracleRptID    string  `gorm:"column:oracle_rpt_id;not null" json:"oracle_rpt_id"`
	InstallSoftID  string  `gorm:"column:install_soft_id;not null" json:"install_soft_id"`
	OracleRptType  string  `gorm:"column:oracle_rpt_type;not null" json:"oracle_rpt_type"`
	ProcessStatus  string  `gorm:"column:process_status;not null" json:"process_status"`
	CreateTime     *string `gorm:"column:create_time" json:"create_time"`
	FinishTime     *string `gorm:"column:finish_time" json:"finish_time"`
	OpUser         *string `gorm:"column:op_user" json:"op_user"`
	ErrorInfo      *string `gorm:"column:error_info" json:"error_info"`
	BeginTime      *string `gorm:"column:begin_time" json:"begin_time"`
	EndTime        *string `gorm:"column:end_time" json:"end_time"`
	RptContent     *string `gorm:"column:rpt_content" json:"rpt_content"`
	TimeSpendSec   *int32  `gorm:"column:time_spend_sec" json:"time_spend_sec"`
	SnapIDBeg      *string `gorm:"column:snap_id_beg" json:"snap_id_beg"`
	SnapIDEnd      *string `gorm:"column:snap_id_end" json:"snap_id_end"`
	Comments       *string `gorm:"column:comments" json:"comments"`
	StaticHTMLPath *string `gorm:"column:static_html_path" json:"static_html_path"`
}

// TableName OracleRpt's table name
func (*OracleRpt) TableName() string {
	return TableNameOracleRpt
}

func (*OracleRpt) PrimaryKey() []string {
	return []string{}
}