// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProductLine = "product_line"

// ProductLine mapped from table <product_line>
type ProductLine struct {
	ProductLine       *string `gorm:"column:product_line" json:"product_line"`     // 产品线
	ProductDomain     *string `gorm:"column:product_domain" json:"product_domain"` // 产品域
	ProductDomainID   string  `gorm:"column:product_domain_id;primaryKey" json:"product_domain_id"`
	ProductLineName   *string `gorm:"column:product_line_name" json:"product_line_name"`     // 产品线名
	ProductDomainName *string `gorm:"column:product_domain_name" json:"product_domain_name"` // 产品域名
}

// TableName ProductLine's table name
func (*ProductLine) TableName() string {
	return TableNameProductLine
}

func (*ProductLine) PrimaryKey() []string {
	return []string{"product_domain_id"}
}