// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameServerInstance = "server_instance"

// ServerInstance mapped from table <server_instance>
type ServerInstance struct {
	ServerID    string  `gorm:"column:server_id;primaryKey" json:"server_id"` // 主键
	ServerEnvID string  `gorm:"column:server_env_id;not null" json:"server_env_id"`
	ServerIP    string  `gorm:"column:server_ip;not null" json:"server_ip"`
	ServerName  *string `gorm:"column:server_name" json:"server_name"`
	ServerPort  string  `gorm:"column:server_port;not null" json:"server_port"`
	ServerUser  *string `gorm:"column:server_user" json:"server_user"`
	ServerPwd   *string `gorm:"column:server_pwd" json:"server_pwd"`
	ServerStatu *string `gorm:"column:server_statu" json:"server_statu"` // 服务器状态 1、正常 0、异常
	Notes       *string `gorm:"column:notes" json:"notes"`               // 备注
	SuperUser   *string `gorm:"column:super_user" json:"super_user"`     // linux超级管理员
	SuperPwd    *string `gorm:"column:super_pwd" json:"super_pwd"`       // linux超级管理员密码
	CheckUser   *string `gorm:"column:check_user" json:"check_user"`     // 用户系统巡检时使用的用户
	CheckPasswd *string `gorm:"column:check_passwd" json:"check_passwd"` // 用户系统巡检时使用的密码
	OraclePwd   *string `gorm:"column:oracle_pwd" json:"oracle_pwd"`     // oracle密码
	/*
		与 sys_server_type关联
		服务提供类型
	*/
	ServerType               *string    `gorm:"column:server_type" json:"server_type"`
	OracleUser               *string    `gorm:"column:oracle_user" json:"oracle_user"` // Oracle用户名
	ServerOs                 *string    `gorm:"column:server_os" json:"server_os"`
	DblinkDump               *string    `gorm:"column:dblink_dump" json:"dblink_dump"`                                    // 用于数据泵导出导出数据时候使用的dblink
	DbaPwd                   *string    `gorm:"column:dba_pwd" json:"dba_pwd"`                                            // 数据库管理员密码
	DbaUser                  *string    `gorm:"column:dba_user" json:"dba_user"`                                          // 数据库管理员用户名
	DbSid                    *string    `gorm:"column:db_sid" json:"db_sid"`                                              // 数据库实例名称，多个用英文逗号分开。
	OsInfo                   *string    `gorm:"column:os_info" json:"os_info"`                                            // 操作系统软硬件信息（废弃）
	ServerGroupID            *string    `gorm:"column:server_group_id" json:"server_group_id"`                            // 关联 server_group_id
	DestVMName               *string    `gorm:"column:dest_vm_name" json:"dest_vm_name"`                                  // vps名称
	SrcVMName                *string    `gorm:"column:src_vm_name" json:"src_vm_name"`                                    // vps 克隆来自于
	CreateTime               *time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 记录创建时间（数据库自动写入）
	ModifyTime               *time.Time `gorm:"column:modify_time;not null;default:CURRENT_TIMESTAMP" json:"modify_time"` // 记录修改时间（数据库自动写入）
	Comments                 *string    `gorm:"column:comments" json:"comments"`                                          // 备注说明
	ZabbixHostid             *string    `gorm:"column:zabbix_hostid" json:"zabbix_hostid"`                                // 对应的zabbix hostid
	ServerHardwareID         *string    `gorm:"column:server_hardware_id" json:"server_hardware_id"`                      // 关联server_hardware.server_hardware_id
	ServerVirtualizationType *string    `gorm:"column:server_virtualization_type" json:"server_virtualization_type"`      // 主机类型见码表
	ServerServiceType        *string    `gorm:"column:server_service_type" json:"server_service_type"`                    // 提供的服务类型分类
	ServerOsUsersID          *string    `gorm:"column:server_os_users_id" json:"server_os_users_id"`                      // 操作系统用户 （server_os_users.server_os_users_id）
	VMHostsID                *string    `gorm:"column:vm_hosts_id" json:"vm_hosts_id"`                                    // vm_hosts.vm_hosts_id
	InternetAddress          *string    `gorm:"column:internet_address" json:"internet_address"`
	IsActived                *string    `gorm:"column:is_actived" json:"is_actived"`
	Location                 *string    `gorm:"column:location" json:"location"`
	ServerOsVersion          *string    `gorm:"column:server_os_version" json:"server_os_version"`
	IsDel                    *string    `gorm:"column:is_del" json:"is_del"`
	OsLogPath                *string    `gorm:"column:os_log_path" json:"os_log_path"`
	ConnectProtocolType      *string    `gorm:"column:connect_protocol_type" json:"connect_protocol_type"`
	ServerBusiName           *string    `gorm:"column:server_busi_name" json:"server_busi_name"`
	ProfessionalName         *string    `gorm:"column:professional_name" json:"professional_name"`
	MemorySize               *string    `gorm:"column:memory_size" json:"memory_size"`
	DiskTotalSize            *string    `gorm:"column:disk_total_size" json:"disk_total_size"`
	CPUCores                 *string    `gorm:"column:cpu_cores" json:"cpu_cores"`
	CPULogicCount            *string    `gorm:"column:cpu_logic_count" json:"cpu_logic_count"`
	IsEnable                 *string    `gorm:"column:is_enable" json:"is_enable"`
	Vip                      *string    `gorm:"column:vip" json:"vip"`
}

// TableName ServerInstance's table name
func (*ServerInstance) TableName() string {
	return TableNameServerInstance
}

func (*ServerInstance) PrimaryKey() []string {
	return []string{"server_id"}
}