// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSqlAdminWebsqlrule = "sql_admin_websqlrule"

// SqlAdminWebsqlrule mapped from table <sql_admin_websqlrule>
type SqlAdminWebsqlrule struct {
	ID            string  `gorm:"column:id;primaryKey" json:"id"`
	Username      *string `gorm:"column:username" json:"username"`
	Privilegetype string  `gorm:"column:privilegetype;not null" json:"privilegetype"`
	Value         *string `gorm:"column:value" json:"value"`
	Minvalue      string  `gorm:"column:minvalue;not null" json:"minvalue"`
	Maxvalue      *string `gorm:"column:maxvalue" json:"maxvalue"`
	Valid         *string `gorm:"column:valid" json:"valid"`
	UserGroupID   *string `gorm:"column:user_group_id" json:"user_group_id"`
}

// TableName SqlAdminWebsqlrule's table name
func (*SqlAdminWebsqlrule) TableName() string {
	return TableNameSqlAdminWebsqlrule
}

func (*SqlAdminWebsqlrule) PrimaryKey() []string {
	return []string{"id"}
}