// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSqlScriptLabelRelation = "sql_script_label_relation"

// SqlScriptLabelRelation mapped from table <sql_script_label_relation>
type SqlScriptLabelRelation struct {
	Label                    string     `gorm:"column:label;not null" json:"label"`
	SqlScriptID              *string    `gorm:"column:sql_script_id" json:"sql_script_id"`
	SqlScriptLabelRelationID string     `gorm:"column:sql_script_label_relation_id;primaryKey" json:"sql_script_label_relation_id"`
	CreateTime               *time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 记录创建时间（数据库自动写入）
}

// TableName SqlScriptLabelRelation's table name
func (*SqlScriptLabelRelation) TableName() string {
	return TableNameSqlScriptLabelRelation
}

func (*SqlScriptLabelRelation) PrimaryKey() []string {
	return []string{"sql_script_label_relation_id"}
}