// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysTokenBusiness = "sys_token_business"

// SysTokenBusiness mapped from table <sys_token_business>
type SysTokenBusiness struct {
	SysTokenBusinessID string  `gorm:"column:sys_token_business_id;primaryKey" json:"sys_token_business_id"` // ID
	SysTokenID         *string `gorm:"column:sys_token_id" json:"sys_token_id"`                              // ID
	BusinessName       *string `gorm:"column:business_name" json:"business_name"`                            // 码表值business_name
}

// TableName SysTokenBusiness's table name
func (*SysTokenBusiness) TableName() string {
	return TableNameSysTokenBusiness
}

func (*SysTokenBusiness) PrimaryKey() []string {
	return []string{"sys_token_business_id"}
}