// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysFormFields = "sys_form_fields"

// SysFormFields mapped from table <sys_form_fields>
type SysFormFields struct {
	SysFormFieldsID      string  `gorm:"column:sys_form_fields_id;not null" json:"sys_form_fields_id"`
	SysFormID            *string `gorm:"column:sys_form_id" json:"sys_form_id"`
	FormKey              *string `gorm:"column:form_key" json:"form_key"`
	FormKeyLabel         *string `gorm:"column:form_key_label" json:"form_key_label"`
	FormKeyDesc          *string `gorm:"column:form_key_desc" json:"form_key_desc"`
	FormKeyType          *string `gorm:"column:form_key_type" json:"form_key_type"`
	FormKeyOrd           *int32  `gorm:"column:form_key_ord" json:"form_key_ord"`
	FormKeyRequired      *int32  `gorm:"column:form_key_required" json:"form_key_required"`
	FormKeyDefaultVal    *string `gorm:"column:form_key_default_val" json:"form_key_default_val"`
	FormKeyInputSrc      *string `gorm:"column:form_key_input_src" json:"form_key_input_src"`
	FormKeyInputSrcValue *string `gorm:"column:form_key_input_src_value" json:"form_key_input_src_value"`
	FormKeyEditor        *string `gorm:"column:form_key_editor" json:"form_key_editor"`
}

// TableName SysFormFields's table name
func (*SysFormFields) TableName() string {
	return TableNameSysFormFields
}

func (*SysFormFields) PrimaryKey() []string {
	return []string{}
}