// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUpgradePlanDbscript = "upgrade_plan_dbscript"

// UpgradePlanDbscript mapped from table <upgrade_plan_dbscript>
type UpgradePlanDbscript struct {
	UpgradePlanDbscriptID string     `gorm:"column:upgrade_plan_dbscript_id;primaryKey" json:"upgrade_plan_dbscript_id"` // 计划单id
	DbscriptEventID       string     `gorm:"column:dbscript_event_id;not null" json:"dbscript_event_id"`                 // 用户id
	UpgradePlanID         string     `gorm:"column:upgrade_plan_id;not null" json:"upgrade_plan_id"`
	IsRight               *string    `gorm:"column:isRight" json:"isRight"`
	CreateTime            *time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 记录创建时间（数据库自动写入）
	ModifyTime            *time.Time `gorm:"column:modify_time;not null;default:CURRENT_TIMESTAMP" json:"modify_time"` // 记录修改时间（数据库自动写入）
	Comments              *string    `gorm:"column:comments" json:"comments"`                                          // 备注说明
}

// TableName UpgradePlanDbscript's table name
func (*UpgradePlanDbscript) TableName() string {
	return TableNameUpgradePlanDbscript
}

func (*UpgradePlanDbscript) PrimaryKey() []string {
	return []string{"upgrade_plan_dbscript_id"}
}