// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWebsocketMsgPid = "websocket_msg_pid"

// WebsocketMsgPid mapped from table <websocket_msg_pid>
type WebsocketMsgPid struct {
	MsgID      string     `gorm:"column:msg_id;not null" json:"msg_id"` // 每个进程发送记录
	Pid        *string    `gorm:"column:pid" json:"pid"`                // 客户端对象序列化
	ID         int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreateTime *time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 记录创建时间（数据库自动写入）
	ModifyTime *time.Time `gorm:"column:modify_time;not null;default:CURRENT_TIMESTAMP" json:"modify_time"` // 记录修改时间（数据库自动写入）
	Comments   *string    `gorm:"column:comments" json:"comments"`                                          // 备注说明
}

// TableName WebsocketMsgPid's table name
func (*WebsocketMsgPid) TableName() string {
	return TableNameWebsocketMsgPid
}

func (*WebsocketMsgPid) PrimaryKey() []string {
	return []string{"id"}
}